export const GET_BUSINESS_WORKING_DAYS_REQUEST =
  "GET_BUSINESS_WORKING_DAYS_REQUEST";
export const GET_BUSINESS_WORKING_DAYS_SUCCESS =
  "GET_BUSINESS_WORKING_DAYS_SUCCESS";
export const GET_BUSINESS_WORKING_DAYS_FAIL = "GET_BUSINESS_WORKING_DAYS_FAIL";
export const GET_BUSINESS_WORKING_DAYS_RESET =
  "GET_BUSINESS_WORKING_DAYS_RESET";

export const UPDATE_BUSINESS_WORKING_DAYS_REQUEST =
  "UPDATE_BUSINESS_WORKING_DAYS_REQUEST";
export const UPDATE_BUSINESS_WORKING_DAYS_SUCCESS =
  "UPDATE_BUSINESS_WORKING_DAYS_SUCCESS";
export const UPDATE_BUSINESS_WORKING_DAYS_FAIL =
  "UPDATE_BUSINESS_WORKING_DAYS_FAIL";
export const UPDATE_BUSINESS_WORKING_DAYS_RESET =
  "UPDATE_BUSINESS_WORKING_DAYS_RESET";

export const UPDATE_BUSINESS_LOGO_REQUEST = "UPDATE_BUSINESS_LOGO_REQUEST";
export const UPDATE_BUSINESS_LOGO_SUCCESS = "UPDATE_BUSINESS_LOGO_SUCCESS";
export const UPDATE_BUSINESS_LOGO_FAIL = "UPDATE_BUSINESS_LOGO_FAIL";

export const UPDATE_BUSINESS_BACKGROUND_REQUEST =
  "UPDATE_BUSINESS_BACKGROUND_REQUEST";
export const UPDATE_BUSINESS_BACKGROUND_SUCCESS =
  "UPDATE_BUSINESS_BACKGROUND_SUCCESS";
export const UPDATE_BUSINESS_BACKGROUND_FAIL =
  "UPDATE_BUSINESS_BACKGROUND_FAIL";

export const UPDATE_BUSINESS_NAME_REQUEST = "UPDATE_BUSINESS_NAME_REQUEST";
export const UPDATE_BUSINESS_NAME_SUCCESS = "UPDATE_BUSINESS_NAME_SUCCESS";
export const UPDATE_BUSINESS_NAME_FAIL = "UPDATE_BUSINESS_NAME_FAIL";

export const UPDATE_BUSINESS_SLOGAN_REQUEST = "UPDATE_BUSINESS_SLOGAN_REQUEST";
export const UPDATE_BUSINESS_SLOGAN_SUCCESS = "UPDATE_BUSINESS_SLOGAN_SUCCESS";
export const UPDATE_BUSINESS_SLOGAN_FAIL = "UPDATE_BUSINESS_SLOGAN_FAIL";
