export const BUSINESS_LOGIN_REQUEST = "BUSINESS_LOGIN_REQUEST";
export const BUSINESS_LOGIN_SUCCESS = "BUSINESS_LOGIN_SUCCESS";
export const BUSINESS_LOGIN_FAIL = "BUSINESS_LOGIN_FAIL";
export const BUSINESS_LOGOUT = "BUSINESS_LOGOUT";
