export const GET_BUSINESS_WORKING_DAYS_REQUEST =
  "GET_BUSINESS_WORKING_DAYS_REQUEST";
export const GET_BUSINESS_WORKING_DAYS_SUCCESS =
  "GET_BUSINESS_WORKING_DAYS_SUCCESS";
export const GET_BUSINESS_WORKING_DAYS_FAIL = "GET_BUSINESS_WORKING_DAYS_FAIL";
export const GET_BUSINESS_WORKING_DAYS_RESET =
  "GET_BUSINESS_WORKING_DAYS_RESET";
